# Generated by Django 5.1 on 2024-08-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeCleaningService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('polishing', 'Polishing'), ('deep_cleaning', 'Deep Cleaning'), ('premium_cleaning', 'Premium Cleaning'), ('regular_cleaning', 'Regular Cleaning')], max_length=50)),
                ('description1', models.CharField(max_length=255)),
                ('description2', models.CharField(blank=True, max_length=255, null=True)),
                ('description3', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
