# Generated by Django 5.1 on 2024-08-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticApp', '0002_shoecleaningservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blogs/')),
                ('badge', models.CharField(max_length=100)),
                ('misc_info', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
