# Generated by Django 5.1 on 2024-08-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticApp', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/additional/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list', models.JSONField(blank=True, null=True)),
                ('additional_images', models.ManyToManyField(blank=True, to='arcticApp.additionalimage')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='arcticApp.blog')),
                ('videos', models.ManyToManyField(blank=True, to='arcticApp.video')),
            ],
        ),
    ]
