# Generated by Django 5.1 on 2024-08-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcticApp', '0004_additionalimage_video_blogdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetails',
            name='price_list',
        ),
    ]
