# Generated by Django 5.1 on 2024-08-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcticApp', '0006_mediacontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetails',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='blogdetails',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogdetails',
            name='videos',
        ),
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
        migrations.DeleteModel(
            name='BlogDetails',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
