# Generated by Django 4.2.4 on 2024-08-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticApp', '0010_productcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='founders_images/')),
                ('description_1', models.TextField()),
                ('description_2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
