# Generated by Django 4.2.4 on 2024-08-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticApp', '0012_displayimage_sitelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alerts/')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('deep_cleaning', 'Deep Cleaning'), ('shoe_polishing', 'Shoe Polishing'), ('odor_removal', 'Odor Removal'), ('waterproofing', 'Waterproofing')], max_length=50)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.TextField()),
            ],
        ),
    ]
