# Generated by Django 4.2.4 on 2024-09-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticApp', '0014_healthheaderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='class_images/')),
                ('alt_text', models.CharField(default='class', max_length=100)),
                ('css_class', models.CharField(default='class__img-1', max_length=50)),
            ],
        ),
    ]
