# Generated by Django 4.2.4 on 2024-09-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticApp', '0015_classimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
